/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file will be auto-generated by TanStack Router

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedImport } from './routes/_authed'
import { Route as AuthedBoardImport } from './routes/_authed/board'
import { Route as AuthedDashboardImport } from './routes/_authed/dashboard'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const AuthedBoardRoute = AuthedBoardImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDashboardRoute = AuthedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof AuthedBoardRoute
  '/dashboard': typeof AuthedDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof AuthedBoardRoute
  '/dashboard': typeof AuthedDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRoute
  '/_authed/board': typeof AuthedBoardRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board' | '/dashboard'
  id: '__root__' | '/' | '/_authed' | '/_authed/board' | '/_authed/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/board",
        "/_authed/dashboard"
      ]
    },
    "/_authed/board": {
      "filePath": "_authed/board.tsx",
      "parent": "/_authed"
    },
    "/_authed/dashboard": {
      "filePath": "_authed/dashboard.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */

interface AuthedRouteChildren {
  AuthedBoardRoute: typeof AuthedBoardRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBoardRoute: AuthedBoardRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren = AuthedRoute._addFileChildren(AuthedRouteChildren)
