// Types-only export - safe for client-side imports
// This file only exports types, no runtime code that uses Node.js modules

export type {
  UserProfile,
  UserProfileInsert,
  Portfolio,
  PortfolioInsert,
  UserPortfolio,
  UserPortfolioInsert,
  Property,
  PropertyInsert,
  PropertyCharacteristics,
  PropertyCharacteristicsInsert,
  PropertyValuation,
  PropertyValuationInsert,
  PropertyAcquisition,
  PropertyAcquisitionInsert,
  PropertyRentalIncome,
  PropertyRentalIncomeInsert,
  PropertyOperatingExpenses,
  PropertyOperatingExpensesInsert,
  PropertyManagement,
  PropertyManagementInsert,
  Loan,
  LoanInsert,
  LoanHistory,
  LoanHistoryInsert,
  PropertyHistory,
  PropertyHistoryInsert,
  PropertyTransaction,
  PropertyTransactionInsert,
  ApiCache,
  ApiCacheInsert,
  PropertyBankAccount,
  PropertyBankAccountInsert,
  PropertyDocument,
  PropertyDocumentInsert,
  // Forge types
  ForgeMilestone,
  ForgeMilestoneInsert,
  ForgeProject,
  ForgeProjectInsert,
  ForgeTicket,
  ForgeTicketInsert,
  ForgeSubtask,
  ForgeSubtaskInsert,
  ForgeReference,
  ForgeReferenceInsert,
  ForgeAgentExecution,
  ForgeAgentExecutionInsert,
  ForgeFileLock,
  ForgeFileLockInsert,
  ForgeTokenUsage,
  ForgeTokenUsageInsert,
  ForgeTokenBudget,
  ForgeTokenBudgetInsert,
  ForgeRegistry,
  ForgeRegistryInsert,
  ForgeDecision,
  ForgeDecisionInsert,
  ForgeDecisionApplication,
  ForgeDecisionApplicationInsert,
  ForgeTicketComment,
  ForgeTicketCommentInsert,
  ForgeTestPersona,
  ForgeTestPersonaInsert,
  ForgeRelease,
  ForgeReleaseInsert,
  ForgeDeployment,
  ForgeDeploymentInsert,
  ForgeSuccessMetric,
  ForgeSuccessMetricInsert,
} from "./types";

// Re-export schema types (these are just type definitions, no runtime code)
export type * from "./schema";

