/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationAcceptRouteImport } from './routes/invitation/accept'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAnalysisRouteImport } from './routes/_public/analysis'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthedWealthJourneyRouteImport } from './routes/_authed/wealth-journey'
import { Route as AuthedPropertyHubRouteImport } from './routes/_authed/property-hub'
import { Route as AuthedExploreRouteImport } from './routes/_authed/explore'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AuthedPropertyHubAddRouteImport } from './routes/_authed/property-hub.add'
import { Route as AuthedPropertyHubPropertyIdRouteImport } from './routes/_authed/property-hub.$propertyId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as AuthedPropertyHubPropertyIdIndexRouteImport } from './routes/_authed/property-hub.$propertyId/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AuthedPropertyHubPropertyIdStrategyRouteImport } from './routes/_authed/property-hub.$propertyId/strategy'
import { Route as AuthedPropertyHubPropertyIdSettingsRouteImport } from './routes/_authed/property-hub.$propertyId/settings'
import { Route as AuthedPropertyHubPropertyIdManagementRouteImport } from './routes/_authed/property-hub.$propertyId/management'
import { Route as AuthedPropertyHubPropertyIdLegalRouteImport } from './routes/_authed/property-hub.$propertyId/legal'
import { Route as AuthedPropertyHubPropertyIdFinancialsRouteImport } from './routes/_authed/property-hub.$propertyId/financials'
import { Route as AuthedPropertyHubPropertyIdDocumentsRouteImport } from './routes/_authed/property-hub.$propertyId/documents'
import { Route as AuthedPropertyHubPropertyIdCommunicationsRouteImport } from './routes/_authed/property-hub.$propertyId/communications'
import { Route as AuthedPropertyHubPropertyIdAnalyticsRouteImport } from './routes/_authed/property-hub.$propertyId/analytics'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationAcceptRoute = InvitationAcceptRouteImport.update({
  id: '/invitation/accept',
  path: '/invitation/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAnalysisRoute = PublicAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedWealthJourneyRoute = AuthedWealthJourneyRouteImport.update({
  id: '/wealth-journey',
  path: '/wealth-journey',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPropertyHubRoute = AuthedPropertyHubRouteImport.update({
  id: '/property-hub',
  path: '/property-hub',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExploreRoute = AuthedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPropertyHubAddRoute = AuthedPropertyHubAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthedPropertyHubRoute,
} as any)
const AuthedPropertyHubPropertyIdRoute =
  AuthedPropertyHubPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => AuthedPropertyHubRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPropertyHubPropertyIdIndexRoute =
  AuthedPropertyHubPropertyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedPropertyHubPropertyIdRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPropertyHubPropertyIdStrategyRoute =
  AuthedPropertyHubPropertyIdStrategyRouteImport.update({
    id: '/strategy',
    path: '/strategy',
    getParentRoute: () => AuthedPropertyHubPropertyIdRoute,
  } as any)
const AuthedPropertyHubPropertyIdSettingsRoute =
  AuthedPropertyHubPropertyIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedPropertyHubPropertyIdRoute,
  } as any)
const AuthedPropertyHubPropertyIdManagementRoute =
  AuthedPropertyHubPropertyIdManagementRouteImport.update({
    id: '/management',
    path: '/management',
    getParentRoute: () => AuthedPropertyHubPropertyIdRoute,
  } as any)
const AuthedPropertyHubPropertyIdLegalRoute =
  AuthedPropertyHubPropertyIdLegalRouteImport.update({
    id: '/legal',
    path: '/legal',
    getParentRoute: () => AuthedPropertyHubPropertyIdRoute,
  } as any)
const AuthedPropertyHubPropertyIdFinancialsRoute =
  AuthedPropertyHubPropertyIdFinancialsRouteImport.update({
    id: '/financials',
    path: '/financials',
    getParentRoute: () => AuthedPropertyHubPropertyIdRoute,
  } as any)
const AuthedPropertyHubPropertyIdDocumentsRoute =
  AuthedPropertyHubPropertyIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthedPropertyHubPropertyIdRoute,
  } as any)
const AuthedPropertyHubPropertyIdCommunicationsRoute =
  AuthedPropertyHubPropertyIdCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthedPropertyHubPropertyIdRoute,
  } as any)
const AuthedPropertyHubPropertyIdAnalyticsRoute =
  AuthedPropertyHubPropertyIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthedPropertyHubPropertyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/explore': typeof AuthedExploreRoute
  '/property-hub': typeof AuthedPropertyHubRouteWithChildren
  '/wealth-journey': typeof AuthedWealthJourneyRoute
  '/about': typeof PublicAboutRoute
  '/analysis': typeof PublicAnalysisRoute
  '/contact': typeof PublicContactRoute
  '/pricing': typeof PublicPricingRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invitation/accept': typeof InvitationAcceptRoute
  '/property-hub/$propertyId': typeof AuthedPropertyHubPropertyIdRouteWithChildren
  '/property-hub/add': typeof AuthedPropertyHubAddRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/property-hub/$propertyId/analytics': typeof AuthedPropertyHubPropertyIdAnalyticsRoute
  '/property-hub/$propertyId/communications': typeof AuthedPropertyHubPropertyIdCommunicationsRoute
  '/property-hub/$propertyId/documents': typeof AuthedPropertyHubPropertyIdDocumentsRoute
  '/property-hub/$propertyId/financials': typeof AuthedPropertyHubPropertyIdFinancialsRoute
  '/property-hub/$propertyId/legal': typeof AuthedPropertyHubPropertyIdLegalRoute
  '/property-hub/$propertyId/management': typeof AuthedPropertyHubPropertyIdManagementRoute
  '/property-hub/$propertyId/settings': typeof AuthedPropertyHubPropertyIdSettingsRoute
  '/property-hub/$propertyId/strategy': typeof AuthedPropertyHubPropertyIdStrategyRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/property-hub/$propertyId/': typeof AuthedPropertyHubPropertyIdIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/explore': typeof AuthedExploreRoute
  '/property-hub': typeof AuthedPropertyHubRouteWithChildren
  '/wealth-journey': typeof AuthedWealthJourneyRoute
  '/about': typeof PublicAboutRoute
  '/analysis': typeof PublicAnalysisRoute
  '/contact': typeof PublicContactRoute
  '/pricing': typeof PublicPricingRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invitation/accept': typeof InvitationAcceptRoute
  '/property-hub/add': typeof AuthedPropertyHubAddRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/property-hub/$propertyId/analytics': typeof AuthedPropertyHubPropertyIdAnalyticsRoute
  '/property-hub/$propertyId/communications': typeof AuthedPropertyHubPropertyIdCommunicationsRoute
  '/property-hub/$propertyId/documents': typeof AuthedPropertyHubPropertyIdDocumentsRoute
  '/property-hub/$propertyId/financials': typeof AuthedPropertyHubPropertyIdFinancialsRoute
  '/property-hub/$propertyId/legal': typeof AuthedPropertyHubPropertyIdLegalRoute
  '/property-hub/$propertyId/management': typeof AuthedPropertyHubPropertyIdManagementRoute
  '/property-hub/$propertyId/settings': typeof AuthedPropertyHubPropertyIdSettingsRoute
  '/property-hub/$propertyId/strategy': typeof AuthedPropertyHubPropertyIdStrategyRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/property-hub/$propertyId': typeof AuthedPropertyHubPropertyIdIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/explore': typeof AuthedExploreRoute
  '/_authed/property-hub': typeof AuthedPropertyHubRouteWithChildren
  '/_authed/wealth-journey': typeof AuthedWealthJourneyRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/analysis': typeof PublicAnalysisRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invitation/accept': typeof InvitationAcceptRoute
  '/_authed/property-hub/$propertyId': typeof AuthedPropertyHubPropertyIdRouteWithChildren
  '/_authed/property-hub/add': typeof AuthedPropertyHubAddRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_authed/property-hub/$propertyId/analytics': typeof AuthedPropertyHubPropertyIdAnalyticsRoute
  '/_authed/property-hub/$propertyId/communications': typeof AuthedPropertyHubPropertyIdCommunicationsRoute
  '/_authed/property-hub/$propertyId/documents': typeof AuthedPropertyHubPropertyIdDocumentsRoute
  '/_authed/property-hub/$propertyId/financials': typeof AuthedPropertyHubPropertyIdFinancialsRoute
  '/_authed/property-hub/$propertyId/legal': typeof AuthedPropertyHubPropertyIdLegalRoute
  '/_authed/property-hub/$propertyId/management': typeof AuthedPropertyHubPropertyIdManagementRoute
  '/_authed/property-hub/$propertyId/settings': typeof AuthedPropertyHubPropertyIdSettingsRoute
  '/_authed/property-hub/$propertyId/strategy': typeof AuthedPropertyHubPropertyIdStrategyRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/_authed/property-hub/$propertyId/': typeof AuthedPropertyHubPropertyIdIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/explore'
    | '/property-hub'
    | '/wealth-journey'
    | '/about'
    | '/analysis'
    | '/contact'
    | '/pricing'
    | '/demo/clerk'
    | '/demo/drizzle'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/invitation/accept'
    | '/property-hub/$propertyId'
    | '/property-hub/add'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/property-hub/$propertyId/analytics'
    | '/property-hub/$propertyId/communications'
    | '/property-hub/$propertyId/documents'
    | '/property-hub/$propertyId/financials'
    | '/property-hub/$propertyId/legal'
    | '/property-hub/$propertyId/management'
    | '/property-hub/$propertyId/settings'
    | '/property-hub/$propertyId/strategy'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/property-hub/$propertyId/'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/explore'
    | '/property-hub'
    | '/wealth-journey'
    | '/about'
    | '/analysis'
    | '/contact'
    | '/pricing'
    | '/demo/clerk'
    | '/demo/drizzle'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/invitation/accept'
    | '/property-hub/add'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/property-hub/$propertyId/analytics'
    | '/property-hub/$propertyId/communications'
    | '/property-hub/$propertyId/documents'
    | '/property-hub/$propertyId/financials'
    | '/property-hub/$propertyId/legal'
    | '/property-hub/$propertyId/management'
    | '/property-hub/$propertyId/settings'
    | '/property-hub/$propertyId/strategy'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/property-hub/$propertyId'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_public'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/dashboard'
    | '/_authed/explore'
    | '/_authed/property-hub'
    | '/_authed/wealth-journey'
    | '/_public/about'
    | '/_public/analysis'
    | '/_public/contact'
    | '/_public/pricing'
    | '/demo/clerk'
    | '/demo/drizzle'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/invitation/accept'
    | '/_authed/property-hub/$propertyId'
    | '/_authed/property-hub/add'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_authed/property-hub/$propertyId/analytics'
    | '/_authed/property-hub/$propertyId/communications'
    | '/_authed/property-hub/$propertyId/documents'
    | '/_authed/property-hub/$propertyId/financials'
    | '/_authed/property-hub/$propertyId/legal'
    | '/_authed/property-hub/$propertyId/management'
    | '/_authed/property-hub/$propertyId/settings'
    | '/_authed/property-hub/$propertyId/strategy'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/_authed/property-hub/$propertyId/'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  InvitationAcceptRoute: typeof InvitationAcceptRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/accept': {
      id: '/invitation/accept'
      path: '/invitation/accept'
      fullPath: '/invitation/accept'
      preLoaderRoute: typeof InvitationAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/analysis': {
      id: '/_public/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof PublicAnalysisRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/wealth-journey': {
      id: '/_authed/wealth-journey'
      path: '/wealth-journey'
      fullPath: '/wealth-journey'
      preLoaderRoute: typeof AuthedWealthJourneyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/property-hub': {
      id: '/_authed/property-hub'
      path: '/property-hub'
      fullPath: '/property-hub'
      preLoaderRoute: typeof AuthedPropertyHubRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/explore': {
      id: '/_authed/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthedExploreRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/property-hub/add': {
      id: '/_authed/property-hub/add'
      path: '/add'
      fullPath: '/property-hub/add'
      preLoaderRoute: typeof AuthedPropertyHubAddRouteImport
      parentRoute: typeof AuthedPropertyHubRoute
    }
    '/_authed/property-hub/$propertyId': {
      id: '/_authed/property-hub/$propertyId'
      path: '/$propertyId'
      fullPath: '/property-hub/$propertyId'
      preLoaderRoute: typeof AuthedPropertyHubPropertyIdRouteImport
      parentRoute: typeof AuthedPropertyHubRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/property-hub/$propertyId/': {
      id: '/_authed/property-hub/$propertyId/'
      path: '/'
      fullPath: '/property-hub/$propertyId/'
      preLoaderRoute: typeof AuthedPropertyHubPropertyIdIndexRouteImport
      parentRoute: typeof AuthedPropertyHubPropertyIdRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/property-hub/$propertyId/strategy': {
      id: '/_authed/property-hub/$propertyId/strategy'
      path: '/strategy'
      fullPath: '/property-hub/$propertyId/strategy'
      preLoaderRoute: typeof AuthedPropertyHubPropertyIdStrategyRouteImport
      parentRoute: typeof AuthedPropertyHubPropertyIdRoute
    }
    '/_authed/property-hub/$propertyId/settings': {
      id: '/_authed/property-hub/$propertyId/settings'
      path: '/settings'
      fullPath: '/property-hub/$propertyId/settings'
      preLoaderRoute: typeof AuthedPropertyHubPropertyIdSettingsRouteImport
      parentRoute: typeof AuthedPropertyHubPropertyIdRoute
    }
    '/_authed/property-hub/$propertyId/management': {
      id: '/_authed/property-hub/$propertyId/management'
      path: '/management'
      fullPath: '/property-hub/$propertyId/management'
      preLoaderRoute: typeof AuthedPropertyHubPropertyIdManagementRouteImport
      parentRoute: typeof AuthedPropertyHubPropertyIdRoute
    }
    '/_authed/property-hub/$propertyId/legal': {
      id: '/_authed/property-hub/$propertyId/legal'
      path: '/legal'
      fullPath: '/property-hub/$propertyId/legal'
      preLoaderRoute: typeof AuthedPropertyHubPropertyIdLegalRouteImport
      parentRoute: typeof AuthedPropertyHubPropertyIdRoute
    }
    '/_authed/property-hub/$propertyId/financials': {
      id: '/_authed/property-hub/$propertyId/financials'
      path: '/financials'
      fullPath: '/property-hub/$propertyId/financials'
      preLoaderRoute: typeof AuthedPropertyHubPropertyIdFinancialsRouteImport
      parentRoute: typeof AuthedPropertyHubPropertyIdRoute
    }
    '/_authed/property-hub/$propertyId/documents': {
      id: '/_authed/property-hub/$propertyId/documents'
      path: '/documents'
      fullPath: '/property-hub/$propertyId/documents'
      preLoaderRoute: typeof AuthedPropertyHubPropertyIdDocumentsRouteImport
      parentRoute: typeof AuthedPropertyHubPropertyIdRoute
    }
    '/_authed/property-hub/$propertyId/communications': {
      id: '/_authed/property-hub/$propertyId/communications'
      path: '/communications'
      fullPath: '/property-hub/$propertyId/communications'
      preLoaderRoute: typeof AuthedPropertyHubPropertyIdCommunicationsRouteImport
      parentRoute: typeof AuthedPropertyHubPropertyIdRoute
    }
    '/_authed/property-hub/$propertyId/analytics': {
      id: '/_authed/property-hub/$propertyId/analytics'
      path: '/analytics'
      fullPath: '/property-hub/$propertyId/analytics'
      preLoaderRoute: typeof AuthedPropertyHubPropertyIdAnalyticsRouteImport
      parentRoute: typeof AuthedPropertyHubPropertyIdRoute
    }
  }
}

interface AuthedPropertyHubPropertyIdRouteChildren {
  AuthedPropertyHubPropertyIdAnalyticsRoute: typeof AuthedPropertyHubPropertyIdAnalyticsRoute
  AuthedPropertyHubPropertyIdCommunicationsRoute: typeof AuthedPropertyHubPropertyIdCommunicationsRoute
  AuthedPropertyHubPropertyIdDocumentsRoute: typeof AuthedPropertyHubPropertyIdDocumentsRoute
  AuthedPropertyHubPropertyIdFinancialsRoute: typeof AuthedPropertyHubPropertyIdFinancialsRoute
  AuthedPropertyHubPropertyIdLegalRoute: typeof AuthedPropertyHubPropertyIdLegalRoute
  AuthedPropertyHubPropertyIdManagementRoute: typeof AuthedPropertyHubPropertyIdManagementRoute
  AuthedPropertyHubPropertyIdSettingsRoute: typeof AuthedPropertyHubPropertyIdSettingsRoute
  AuthedPropertyHubPropertyIdStrategyRoute: typeof AuthedPropertyHubPropertyIdStrategyRoute
  AuthedPropertyHubPropertyIdIndexRoute: typeof AuthedPropertyHubPropertyIdIndexRoute
}

const AuthedPropertyHubPropertyIdRouteChildren: AuthedPropertyHubPropertyIdRouteChildren =
  {
    AuthedPropertyHubPropertyIdAnalyticsRoute:
      AuthedPropertyHubPropertyIdAnalyticsRoute,
    AuthedPropertyHubPropertyIdCommunicationsRoute:
      AuthedPropertyHubPropertyIdCommunicationsRoute,
    AuthedPropertyHubPropertyIdDocumentsRoute:
      AuthedPropertyHubPropertyIdDocumentsRoute,
    AuthedPropertyHubPropertyIdFinancialsRoute:
      AuthedPropertyHubPropertyIdFinancialsRoute,
    AuthedPropertyHubPropertyIdLegalRoute:
      AuthedPropertyHubPropertyIdLegalRoute,
    AuthedPropertyHubPropertyIdManagementRoute:
      AuthedPropertyHubPropertyIdManagementRoute,
    AuthedPropertyHubPropertyIdSettingsRoute:
      AuthedPropertyHubPropertyIdSettingsRoute,
    AuthedPropertyHubPropertyIdStrategyRoute:
      AuthedPropertyHubPropertyIdStrategyRoute,
    AuthedPropertyHubPropertyIdIndexRoute:
      AuthedPropertyHubPropertyIdIndexRoute,
  }

const AuthedPropertyHubPropertyIdRouteWithChildren =
  AuthedPropertyHubPropertyIdRoute._addFileChildren(
    AuthedPropertyHubPropertyIdRouteChildren,
  )

interface AuthedPropertyHubRouteChildren {
  AuthedPropertyHubPropertyIdRoute: typeof AuthedPropertyHubPropertyIdRouteWithChildren
  AuthedPropertyHubAddRoute: typeof AuthedPropertyHubAddRoute
}

const AuthedPropertyHubRouteChildren: AuthedPropertyHubRouteChildren = {
  AuthedPropertyHubPropertyIdRoute:
    AuthedPropertyHubPropertyIdRouteWithChildren,
  AuthedPropertyHubAddRoute: AuthedPropertyHubAddRoute,
}

const AuthedPropertyHubRouteWithChildren =
  AuthedPropertyHubRoute._addFileChildren(AuthedPropertyHubRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedExploreRoute: typeof AuthedExploreRoute
  AuthedPropertyHubRoute: typeof AuthedPropertyHubRouteWithChildren
  AuthedWealthJourneyRoute: typeof AuthedWealthJourneyRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedExploreRoute: AuthedExploreRoute,
  AuthedPropertyHubRoute: AuthedPropertyHubRouteWithChildren,
  AuthedWealthJourneyRoute: AuthedWealthJourneyRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAnalysisRoute: typeof PublicAnalysisRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicPricingRoute: typeof PublicPricingRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAnalysisRoute: PublicAnalysisRoute,
  PublicContactRoute: PublicContactRoute,
  PublicPricingRoute: PublicPricingRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  InvitationAcceptRoute: InvitationAcceptRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
