CREATE TABLE "property_management" (
	"property_id" uuid PRIMARY KEY NOT NULL,
	"is_self_managed" boolean DEFAULT true NOT NULL,
	"company_name" text,
	"company_website" text,
	"contact_name" text,
	"contact_email" text,
	"contact_phone" text,
	"contract_start_date" date,
	"contract_end_date" date,
	"contract_auto_renews" boolean,
	"cancellation_notice_days" integer,
	"fee_type" text DEFAULT 'percentage',
	"fee_percentage" numeric(5, 4),
	"fee_flat_amount" numeric(10, 2),
	"fee_minimum" numeric(10, 2),
	"leasing_fee_type" text,
	"leasing_fee_percentage" numeric(5, 4),
	"leasing_fee_flat" numeric(10, 2),
	"lease_renewal_fee" numeric(10, 2),
	"maintenance_markup_percentage" numeric(5, 4),
	"maintenance_coordination_fee" numeric(10, 2),
	"eviction_fee" numeric(10, 2),
	"early_termination_fee" numeric(10, 2),
	"services_included" text[],
	"payment_method" text,
	"payment_day" integer,
	"holds_security_deposit" boolean,
	"reserve_amount" numeric(10, 2),
	"portal_url" text,
	"portal_username" text,
	"appfolio_property_id" text,
	"buildium_property_id" text,
	"propertyware_property_id" text,
	"notes" text,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "property_management" ADD CONSTRAINT "property_management_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;